//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invstack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Articles
    {
        public tbl_Articles()
        {
            this.tbl_Comments = new HashSet<tbl_Comments>();
        }
    
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Emp_ID { get; set; }
        public string Title { get; set; }
        public string Language { get; set; }
        public string Post { get; set; }
        public string Entry_by { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual tbl_UserDetails tbl_UserDetails { get; set; }
        public virtual ICollection<tbl_Comments> tbl_Comments { get; set; }
    }
}
