//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invstack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Questions
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Emp_id { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public string Question_Description { get; set; }
        public string language { get; set; }
        public Nullable<int> Entry_By { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual tbl_UserDetails tbl_UserDetails { get; set; }
    }
}
