//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invstack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comments
    {
        public int ID { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Emp_ID { get; set; }
        public string Comments { get; set; }
        public string Entry_by { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual tbl_Articles tbl_Articles { get; set; }
        public virtual tbl_UserDetails tbl_UserDetails { get; set; }
    }
}
